#!/usr/bin/env node
// Regenerate src/idl.ts from the IDL `anchor build` writes.
//
//   anchor build                                  # writes target/idl/carrier.json
//   node packages/client/scripts/sync-idl.mjs     # rewrites packages/client/src/idl.ts
//
// The IDL is embedded as TypeScript because *.json is git-ignored in this repo.
// Pass a different path as the first argument to read another IDL file.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const source = process.argv[2] ?? here("../../../target/idl/carrier.json");
const idl = JSON.parse(readFileSync(source, "utf8"));

const out = `// Generated by packages/client/scripts/sync-idl.mjs from the Anchor IDL.
// Do not edit by hand. To regenerate after changing programs/carrier:
//
//   anchor build && node packages/client/scripts/sync-idl.mjs
//
// The client does not load this at runtime to build instructions (it encodes
// Borsh by hand, see instructions.ts), but tests check every discriminator,
// account list and error code against it, so a stale copy fails the suite.

export const IDL = ${JSON.stringify(idl, null, 2)} as const;

export type CarrierIdl = typeof IDL;
`;
writeFileSync(here("../src/idl.ts"), out);
console.log(`wrote src/idl.ts from ${source}`);
