// Generated by packages/client/scripts/sync-idl.mjs from the Anchor IDL.
// Do not edit by hand. To regenerate after changing programs/carrier:
//
//   anchor build && node packages/client/scripts/sync-idl.mjs
//
// The client does not load this at runtime to build instructions (it encodes
// Borsh by hand, see instructions.ts), but tests check every discriminator,
// account list and error code against it, so a stale copy fails the suite.

export const IDL = {
  "address": "CJBPBb6WBPWptmpiW4Kdb7SeRC7Cmob5YAaBtKSMXBvt",
  "metadata": {
    "name": "carrier",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Offline-first value transfer that settles when any carrier reconnects"
  },
  "instructions": [
    {
      "name": "open_pouch",
      "docs": [
        "Commit funds up front so they can be spent with no connectivity."
      ],
      "discriminator": [
        53,
        161,
        172,
        193,
        66,
        142,
        157,
        252
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": true,
          "signer": true
        },
        {
          "name": "pouch",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "funding",
          "writable": true
        },
        {
          "name": "mint"
        },
        {
          "name": "token_program"
        },
        {
          "name": "system_program"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        },
        {
          "name": "bond",
          "type": "u64"
        }
      ]
    },
    {
      "name": "refill_pouch",
      "docs": [
        "Add spendable funds. Does not change the epoch."
      ],
      "discriminator": [
        21,
        90,
        41,
        223,
        50,
        32,
        176,
        240
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": true,
          "signer": true
        },
        {
          "name": "pouch",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "funding",
          "writable": true
        },
        {
          "name": "mint"
        },
        {
          "name": "token_program"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "add_bond",
      "docs": [
        "Add to the slashable bond."
      ],
      "discriminator": [
        67,
        104,
        1,
        227,
        44,
        237,
        39,
        95
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": true,
          "signer": true
        },
        {
          "name": "pouch",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "funding",
          "writable": true
        },
        {
          "name": "mint"
        },
        {
          "name": "token_program"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "advance_epoch",
      "docs": [
        "Start a new epoch, freeing all 256 note slots. Only after the current",
        "epoch has closed and its slashing grace period has passed."
      ],
      "discriminator": [
        93,
        138,
        234,
        218,
        241,
        230,
        132,
        38
      ],
      "accounts": [
        {
          "name": "owner",
          "signer": true
        },
        {
          "name": "pouch",
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "settle_note",
      "docs": [
        "Settle one offline note and pay everyone who carried it."
      ],
      "discriminator": [
        21,
        43,
        198,
        188,
        252,
        22,
        228,
        86
      ],
      "accounts": [
        {
          "name": "settler",
          "docs": [
            "Whoever reconnected first. Pays the transaction fee. Earns nothing from",
            "the note: relay fee nobody earned stays in the vault. Does not need to",
            "be party to the payment."
          ],
          "writable": true,
          "signer": true
        },
        {
          "name": "pouch",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "recipient",
          "writable": true
        },
        {
          "name": "mint"
        },
        {
          "name": "token_program"
        },
        {
          "name": "instructions",
          "docs": [
            "checked `load_instruction_at_checked` helpers."
          ]
        }
      ],
      "args": [
        {
          "name": "note",
          "type": {
            "defined": {
              "name": "Note"
            }
          }
        },
        {
          "name": "hops",
          "type": {
            "vec": {
              "defined": {
                "name": "HopClaim"
              }
            }
          }
        }
      ]
    },
    {
      "name": "begin_settlement",
      "docs": [
        "Open a draft so a long chain can be verified across several transactions."
      ],
      "discriminator": [
        124,
        223,
        80,
        249,
        19,
        59,
        26,
        92
      ],
      "accounts": [
        {
          "name": "settler",
          "writable": true,
          "signer": true
        },
        {
          "name": "pouch"
        },
        {
          "name": "draft",
          "writable": true
        },
        {
          "name": "instructions"
        },
        {
          "name": "system_program"
        }
      ],
      "args": [
        {
          "name": "note",
          "type": {
            "defined": {
              "name": "Note"
            }
          }
        }
      ]
    },
    {
      "name": "extend_settlement",
      "docs": [
        "Verify the next few hops into an open draft."
      ],
      "discriminator": [
        37,
        213,
        212,
        44,
        107,
        158,
        247,
        111
      ],
      "accounts": [
        {
          "name": "settler",
          "writable": true,
          "signer": true
        },
        {
          "name": "draft",
          "writable": true
        },
        {
          "name": "instructions"
        }
      ],
      "args": [
        {
          "name": "claims",
          "type": {
            "vec": {
              "defined": {
                "name": "HopClaim"
              }
            }
          }
        }
      ]
    },
    {
      "name": "finalize_settlement",
      "docs": [
        "Pay out a chain whose every hop has been verified."
      ],
      "discriminator": [
        220,
        72,
        152,
        119,
        178,
        196,
        25,
        170
      ],
      "accounts": [
        {
          "name": "settler",
          "writable": true,
          "signer": true
        },
        {
          "name": "pouch",
          "writable": true
        },
        {
          "name": "draft",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "recipient",
          "writable": true
        },
        {
          "name": "mint"
        },
        {
          "name": "token_program"
        }
      ],
      "args": []
    },
    {
      "name": "abandon_settlement",
      "docs": [
        "Give up on a draft and reclaim its rent."
      ],
      "discriminator": [
        33,
        234,
        164,
        189,
        211,
        182,
        49,
        113
      ],
      "accounts": [
        {
          "name": "settler",
          "writable": true,
          "signer": true
        },
        {
          "name": "draft",
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "close_expired_draft",
      "docs": [
        "Let anyone close a draft whose note has expired. Rent goes to its settler."
      ],
      "discriminator": [
        24,
        224,
        230,
        185,
        158,
        197,
        29,
        120
      ],
      "accounts": [
        {
          "name": "draft",
          "writable": true
        },
        {
          "name": "settler",
          "docs": [
            "settler."
          ],
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "close_pouch",
      "docs": [
        "Recover the unspent balance and bond once the epoch can no longer settle",
        "and the slashing grace period has passed."
      ],
      "discriminator": [
        245,
        201,
        5,
        235,
        249,
        159,
        41,
        196
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": true,
          "signer": true
        },
        {
          "name": "pouch",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "destination",
          "writable": true
        },
        {
          "name": "mint"
        },
        {
          "name": "token_program"
        }
      ],
      "args": []
    },
    {
      "name": "prove_double_spend",
      "docs": [
        "Pay the holder of a note that lost its slot from the sender's bond.",
        "`note_a` settled; `note_b` lost."
      ],
      "discriminator": [
        213,
        100,
        176,
        236,
        193,
        173,
        212,
        56
      ],
      "accounts": [
        {
          "name": "prover",
          "docs": [
            "Anyone. Pays the claim record's rent and gets a tenth of the loss, if",
            "bond is left after the victim."
          ],
          "writable": true,
          "signer": true
        },
        {
          "name": "pouch",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "victim",
          "docs": [
            "A token account of the losing note's recipient. Checked in the handler."
          ],
          "writable": true
        },
        {
          "name": "prover_payout",
          "writable": true
        },
        {
          "name": "claim",
          "docs": [
            "One per losing note. `init` fails if it exists, so a note is paid once."
          ],
          "writable": true
        },
        {
          "name": "mint"
        },
        {
          "name": "token_program"
        },
        {
          "name": "system_program"
        },
        {
          "name": "instructions"
        }
      ],
      "args": [
        {
          "name": "note_a",
          "type": {
            "defined": {
              "name": "Note"
            }
          }
        },
        {
          "name": "note_b",
          "type": {
            "defined": {
              "name": "Note"
            }
          }
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "DoubleSpendClaim",
      "discriminator": [
        89,
        50,
        251,
        108,
        150,
        143,
        178,
        135
      ]
    },
    {
      "name": "Pouch",
      "discriminator": [
        1,
        68,
        34,
        227,
        194,
        225,
        66,
        255
      ]
    },
    {
      "name": "SettlementDraft",
      "discriminator": [
        244,
        34,
        80,
        57,
        95,
        251,
        30,
        93
      ]
    }
  ],
  "types": [
    {
      "name": "BondAdded",
      "type": {
        "fields": [
          {
            "name": "pouch",
            "type": "pubkey"
          },
          {
            "name": "amount",
            "type": "u64"
          },
          {
            "name": "bond",
            "type": "u64"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "DoubleSpendProven",
      "type": {
        "fields": [
          {
            "name": "pouch",
            "type": "pubkey"
          },
          {
            "name": "slot_index",
            "type": "u8"
          },
          {
            "name": "epoch",
            "type": "u32"
          },
          {
            "docs": [
              "The note that settled."
            ],
            "name": "note_a",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "docs": [
              "The note that lost."
            ],
            "name": "note_b",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "docs": [
              "Wallet that held the losing note."
            ],
            "name": "victim",
            "type": "pubkey"
          },
          {
            "name": "paid_victim",
            "type": "u64"
          },
          {
            "name": "paid_prover",
            "type": "u64"
          },
          {
            "name": "bond_left",
            "type": "u64"
          },
          {
            "name": "prover",
            "type": "pubkey"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "EpochAdvanced",
      "type": {
        "fields": [
          {
            "name": "pouch",
            "type": "pubkey"
          },
          {
            "name": "epoch",
            "type": "u32"
          },
          {
            "name": "started_at",
            "type": "i64"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "PouchClosed",
      "type": {
        "fields": [
          {
            "name": "pouch",
            "type": "pubkey"
          },
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "returned",
            "type": "u64"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "NoteSettled",
      "type": {
        "fields": [
          {
            "name": "pouch",
            "type": "pubkey"
          },
          {
            "name": "note_hash",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "to",
            "type": "pubkey"
          },
          {
            "name": "amount",
            "type": "u64"
          },
          {
            "name": "slot_index",
            "type": "u8"
          },
          {
            "name": "epoch",
            "type": "u32"
          },
          {
            "docs": [
              "Transmission lineage, sender first. This is what the spread map draws."
            ],
            "name": "lineage",
            "type": {
              "vec": "pubkey"
            }
          },
          {
            "docs": [
              "What the relayers actually received, all of them together."
            ],
            "name": "relay_fee_paid",
            "type": "u64"
          },
          {
            "docs": [
              "Relay fee nobody earned (all of it with no hops, else rounding dust).",
              "It stays in the vault and remains the owner's."
            ],
            "name": "relay_fee_kept",
            "type": "u64"
          },
          {
            "name": "settled_by",
            "type": "pubkey"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "SettlementExtended",
      "type": {
        "fields": [
          {
            "name": "note_hash",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "hops_verified",
            "type": "u8"
          },
          {
            "name": "last_carrier",
            "type": "pubkey"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "SettlementStarted",
      "type": {
        "fields": [
          {
            "name": "pouch",
            "type": "pubkey"
          },
          {
            "name": "note_hash",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "settler",
            "type": "pubkey"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "DoubleSpendClaim",
      "docs": [
        "Marks one losing note as compensated. Its address is",
        "`[\"claim\", pouch, losing_note_hash]`, so each losing note can be claimed",
        "once. Never closed: a closed claim could be claimed again."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "victim",
            "type": "pubkey"
          },
          {
            "name": "paid",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "HopClaim",
      "docs": [
        "A hop as it travels in instruction data.",
        "",
        "Only the two fields that cannot be derived. `note_hash`, `prev` and `seq` are",
        "all implied by the note and the position in the chain, so transmitting them",
        "wastes 65 bytes per hop against a 1232-byte transaction limit — and worse,",
        "makes it possible to send values that disagree with the chain, which the",
        "program then has to check for. Rebuilding them here means they cannot",
        "disagree."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "relayer",
            "type": "pubkey"
          },
          {
            "name": "at",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "Note",
      "docs": [
        "An offline payment. Signed by the pouch owner, carried by strangers, settled",
        "by whoever reconnects first."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "pouch",
            "type": "pubkey"
          },
          {
            "name": "to",
            "type": "pubkey"
          },
          {
            "name": "amount",
            "type": "u64"
          },
          {
            "name": "slot_index",
            "type": "u8"
          },
          {
            "name": "epoch",
            "type": "u32"
          },
          {
            "name": "expiry",
            "type": "i64"
          },
          {
            "name": "relay_fee_bps",
            "type": "u16"
          }
        ]
      }
    },
    {
      "name": "Pouch",
      "docs": [
        "A pre-funded, pre-committed spending allowance that can be spent with no",
        "connectivity. See docs/PROTOCOL.md."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "mint",
            "type": "pubkey"
          },
          {
            "name": "committed",
            "docs": [
              "Total moved into the pouch across all epochs."
            ],
            "type": "u64"
          },
          {
            "name": "settled",
            "docs": [
              "Total already paid out to recipients."
            ],
            "type": "u64"
          },
          {
            "name": "bond",
            "docs": [
              "Slashable stake backing honest behaviour."
            ],
            "type": "u64"
          },
          {
            "name": "epoch",
            "docs": [
              "Notes are only valid for the epoch they name. Starts at the unix time",
              "the pouch was opened and goes up by one on each `advance_epoch`."
            ],
            "type": "u32"
          },
          {
            "name": "epoch_started_at",
            "docs": [
              "When the current epoch began. Notes may not outlive",
              "`epoch_started_at + MAX_NOTE_LIFETIME_SECONDS`, which is what makes the",
              "remaining balance recoverable via `close_pouch`."
            ],
            "type": "i64"
          },
          {
            "name": "spent",
            "docs": [
              "256-bit map of which note slots have settled this epoch.",
              "",
              "A bitmap rather than a monotonic counter because notes in a mesh arrive",
              "out of order — a counter would permanently strand every note below the",
              "high-water mark."
            ],
            "type": {
              "array": [
                "u64",
                4
              ]
            }
          },
          {
            "name": "settled_fp",
            "docs": [
              "For each slot settled this epoch, the fingerprint of the note that took",
              "it (see `note_fingerprint`). This is how `prove_double_spend` tells the",
              "note that was paid from the one that lost."
            ],
            "type": {
              "array": [
                "u64",
                256
              ]
            }
          },
          {
            "name": "bump",
            "type": "u8"
          },
          {
            "name": "vault_bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "SettlementDraft",
      "docs": [
        "Verification-in-progress for one note.",
        "",
        "Signature checking is the expensive part and it does not all fit in one",
        "transaction, so it is accumulated here across several. The draft only ever",
        "holds state the program itself verified: each `extend_settlement` checks the",
        "next hops against the chain recorded so far, so a draft can never describe a",
        "chain nobody signed."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "note",
            "docs": [
              "The note being settled, stored whole so finalising needs no re-supply",
              "(and so the amount cannot change between begin and finalize)."
            ],
            "type": {
              "defined": {
                "name": "Note"
              }
            }
          },
          {
            "name": "note_hash",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "pouch",
            "type": "pubkey"
          },
          {
            "name": "owner",
            "docs": [
              "The pouch owner, kept here so carrier-eligibility can be checked while",
              "extending without having to pass the pouch account to every call."
            ],
            "type": "pubkey"
          },
          {
            "name": "settler",
            "docs": [
              "Who opened the draft, pays its rent, and is refunded when it closes.",
              "Part of the seeds, so two settlers of one note never share a draft."
            ],
            "type": "pubkey"
          },
          {
            "name": "epoch_started_at",
            "docs": [
              "When the note's epoch began, for bounding hop times while extending."
            ],
            "type": "i64"
          },
          {
            "name": "next_seq",
            "docs": [
              "Position the next hop must occupy."
            ],
            "type": "u8"
          },
          {
            "name": "last_carrier",
            "docs": [
              "Who the next hop must name as its predecessor."
            ],
            "type": "pubkey"
          },
          {
            "name": "lineage",
            "type": {
              "vec": "pubkey"
            }
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    }
  ],
  "events": [
    {
      "discriminator": [
        49,
        199,
        208,
        217,
        88,
        186,
        82,
        183
      ],
      "name": "BondAdded"
    },
    {
      "discriminator": [
        63,
        28,
        33,
        213,
        239,
        93,
        135,
        50
      ],
      "name": "DoubleSpendProven"
    },
    {
      "discriminator": [
        41,
        220,
        14,
        123,
        117,
        70,
        117,
        157
      ],
      "name": "EpochAdvanced"
    },
    {
      "discriminator": [
        7,
        26,
        23,
        202,
        70,
        178,
        227,
        141
      ],
      "name": "PouchClosed"
    },
    {
      "discriminator": [
        95,
        180,
        94,
        23,
        84,
        193,
        191,
        107
      ],
      "name": "NoteSettled"
    },
    {
      "discriminator": [
        250,
        141,
        223,
        126,
        194,
        57,
        104,
        90
      ],
      "name": "SettlementExtended"
    },
    {
      "discriminator": [
        131,
        24,
        2,
        55,
        117,
        102,
        209,
        156
      ],
      "name": "SettlementStarted"
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "MalformedSignatureData",
      "msg": "ed25519 precompile instruction data is malformed"
    },
    {
      "code": 6001,
      "name": "UnsupportedSignatureLayout",
      "msg": "signature entry references another instruction, which is not supported"
    },
    {
      "code": 6002,
      "name": "SignatureNotVerified",
      "msg": "required signature was not verified by the ed25519 precompile"
    },
    {
      "code": 6003,
      "name": "PouchMismatch",
      "msg": "note was issued against a different pouch"
    },
    {
      "code": 6004,
      "name": "EpochMismatch",
      "msg": "note was issued against a different pouch epoch"
    },
    {
      "code": 6005,
      "name": "NoteLifetimeTooLong",
      "msg": "note expiry is beyond the maximum lifetime for its epoch"
    },
    {
      "code": 6006,
      "name": "NoteExpired",
      "msg": "note has expired"
    },
    {
      "code": 6007,
      "name": "SlotAlreadySpent",
      "msg": "note slot has already settled; this note is a double spend or a replay"
    },
    {
      "code": 6008,
      "name": "InsufficientCommitted",
      "msg": "pouch has insufficient committed funds remaining"
    },
    {
      "code": 6009,
      "name": "RecipientMismatch",
      "msg": "recipient token account owner does not match the note recipient"
    },
    {
      "code": 6010,
      "name": "TooManyHops",
      "msg": "transmission chain is longer than MAX_HOPS"
    },
    {
      "code": 6011,
      "name": "HopSequenceInvalid",
      "msg": "hop sequence numbers must start at zero and increase by one"
    },
    {
      "code": 6012,
      "name": "HopNoteMismatch",
      "msg": "hop does not reference the note being settled"
    },
    {
      "code": 6013,
      "name": "HopChainBroken",
      "msg": "hop chain is broken: this hop's predecessor is not the previous relayer"
    },
    {
      "code": 6014,
      "name": "RelayerAccountsMismatch",
      "msg": "expected one relayer token account per hop, in hop order"
    },
    {
      "code": 6015,
      "name": "RelayerMismatch",
      "msg": "relayer token account owner does not match the hop relayer"
    },
    {
      "code": 6016,
      "name": "HopTimeOutOfRange",
      "msg": "hop time is before its epoch began or too far in the future"
    },
    {
      "code": 6017,
      "name": "RelayFeeTooHigh",
      "msg": "relay fee exceeds the note amount (relay_fee_bps over 10000)"
    },
    {
      "code": 6018,
      "name": "RepeatedCarrier",
      "msg": "a key appears twice in the transmission chain"
    },
    {
      "code": 6019,
      "name": "SelfDealingCarrier",
      "msg": "the sender or the recipient cannot also be paid as a carrier"
    },
    {
      "code": 6020,
      "name": "NotesIdentical",
      "msg": "double spend proof must reference two different notes"
    },
    {
      "code": 6021,
      "name": "NotesNotConflicting",
      "msg": "double spend proof requires both notes to share pouch, epoch and slot"
    },
    {
      "code": 6022,
      "name": "NothingToSlash",
      "msg": "pouch has no bond remaining to slash"
    },
    {
      "code": 6023,
      "name": "NoteNotSettled",
      "msg": "the first note must be the one that settled in this slot"
    },
    {
      "code": 6024,
      "name": "VictimMismatch",
      "msg": "victim token account is not owned by the losing note's recipient"
    },
    {
      "code": 6025,
      "name": "VictimIsOwner",
      "msg": "the pouch owner cannot be compensated for their own double spend"
    },
    {
      "code": 6026,
      "name": "PouchNotDrainable",
      "msg": "pouch cannot close yet: notes may still settle or a double spend proof may still land"
    },
    {
      "code": 6027,
      "name": "EpochStillOpen",
      "msg": "epoch cannot advance yet: notes may still settle or a double spend proof may still land"
    },
    {
      "code": 6028,
      "name": "DraftNotExpired",
      "msg": "draft note has not expired yet"
    },
    {
      "code": 6029,
      "name": "UnsupportedMintExtension",
      "msg": "mint has a Token-2022 extension this program does not support"
    },
    {
      "code": 6030,
      "name": "MathOverflow",
      "msg": "arithmetic overflow"
    }
  ]
} as const;

export type CarrierIdl = typeof IDL;
